### ISSUE TITLE
Activity containing signature view will crash android version 9

### ISSUE THREAD

**Issue by nitish-nanda** [zahid-ali-shah/SignatureView#19]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:61)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:79)
        at com.kyanogen.signatureview.SignatureView.onDraw(SignatureView.java:287)
        at android.view.View.draw(View.java:20234)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at com.android.internal.policy.DecorView.draw(DecorView.java:784)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3195)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2564)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:888)
        at android.view.Choreographer.doFrame(Choreographer.java:819)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Kratos1996** [comment]
public void setBitmap(Bitmap bitmap) {
        if (bitmap != null) {
            bmp = bitmap;
            Bitmap workingBitmap = Bitmap.createBitmap(bmp);
            Bitmap mutableBitmap = workingBitmap.copy(Bitmap.Config.ARGB_8888, true);
            canvasBmp = new Canvas(mutableBitmap);
           // canvasBmp = new Canvas(bitmap);
            postInvalidate();
        }
    }

**Comment by Kratos1996** [comment]
add this method

**Comment by zahid-ali-shah** [comment]
Thanks for reporting this, but this repo is no longer active. You can create a fork and fix it there or contribute any other popular fork
